permalink: /blog/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

title : Daniel Spósito
tagline: Vivre sans rêve, qu'este-ce?
author :
  name : Daniel Sposito
  github : dsposito
  twitter : smwrxforever

production_url : http://danielsposito.com

JB :
  version : 0.3.0

  BASE_PATH : false
  ASSET_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : false

  analytics :
    provider : false 

  sharing :
    provider : false
